services:
  target:
    container_name: service-target
    build: 
      context: ./target
      args:
        - SSH_TARGET_USER=${SSH_TARGET_USER}
        - SSH_TARGET_PASSWORD=${SSH_TARGET_PASSWORD}
    ports:
      - 22
      - 80
    networks:
      - target

  agent:
    container_name: service-agent
    build: 
      context: ./agent
    environment:
      - SSH_TARGET_USER=${SSH_TARGET_USER}
      - SSH_TARGET_PASSWORD=${SSH_TARGET_PASSWORD}
      - SSH_HOSTNAME=target
      - SSH_PORT=22
      - HTTP_PORT=80
      - APACHE_ERROR_TIMEOUT=10
    ports:
      - 8080:8080
    depends_on:
      - target
    networks:
      - target

networks:
  target:
    driver: bridge
  