services:
  target:
    container_name: service-target
    build: 
      context: ./target
      args:
        - SSH_TARGET_USER=${SSH_TARGET_USER}
        - SSH_TARGET_PASSWORD=${SSH_TARGET_PASSWORD}
    ports:
      - "52022:22"
    networks:
      - target

  agent:
    container_name: service-agent
    build: 
      context: ./agent
    environment:
      - SSH_TARGET_USER=${SSH_TARGET_USER}
      - SSH_TARGET_PASSWORD=${SSH_TARGET_PASSWORD}
      - APACHE_ERROR_TIMEOUT=10
    ports:
      - "8080:8080"
    depends_on:
      - target
    networks:
      - target

networks:
  target:
    driver: bridge
  